[package]
name = "piv1-genesis-production-caller"
version = "0.1.0"
edition = "2021"
rust-version = "1.89"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[workspace]
resolver = "2"

[dependencies]
anchor-lang = "=0.32.1"
piv1 = { path = "../../programs/piv1", features = ["no-entrypoint"] }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
